version: '3.5'

services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - credit-application
      - db
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
  certbot:
      image: certbot/certbot
      depends_on:
        - nginx
      container_name: certbot
      volumes:
        - certbot-etc:/etc/letsencrypt
        - certbot-var:/var/lib/letsencrypt
        - web-root:/var/www/html
      command: certonly --webroot --webroot-path=/var/www/html --email artem.kuryshkin@gmail.com --agree-tos --no-eff-email --staging -d credit.art3m1y.me
  db:
    container_name: db
    ports:
      - "7777:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=DHprGcpMyZ87D1ysBcJNvDF3YBjSNhR7zGR7kB0IZoyd6ZZ7RJ
      - POSTGRES_DB=credit-application
    image: postgres:12.13-alpine3.17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - postgres:/var/lib/postgresql/data
  credit-application:
    image: art3m1y/credit-application:1.0.0
    container_name: credit-application
    ports:
      - "8080:8888"
    environment:
      TOKEN_ACCESS_ACTION_TIME: 30
      TOKEN_ACCESS_SECRET_KEY: ZEofmFV09ofH9ZBp55rGZEofmFV09ofH9ZBp55rGZEofmFV09ofH9ZBp55rG
      TOKEN_REFRESH_ACTION_TIME: 4320
      TOKEN_REFRESH_SECRET_KEY: sap5sap5LjhsJCr60bxquGLXLjhsJsap5LjhsJCr60bxquGLXCr60bxquGLX
      BACKEND_URL: https://localhost:8888
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: admin
      POSTGRES_DB: credit-application
      POSTGRES_PASSWORD: DHprGcpMyZ87D1ysBcJNvDF3YBjSNhR7zGR7kB0IZoyd6ZZ7RJ
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres:
  certbot-etc:
  certbot-var:
  web-root:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /tmp/dhparam/
      o: bind
