version: '3.5'

services:
  db:
    container_name: db
    ports:
      - "7777:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=02QTRMa49smtrR2PLQNnaThVMo9AFh
      - POSTGRES_DB=CreditApplicationDB
    image: postgres:12.13-alpine3.17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
  postgres:
