version: '3.5'

services:
  db:
    container_name: db
    ports:
      - "7777:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:12.13-alpine3.17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - postgres:/var/lib/postgresql/data


volumes:
  postgres:
